stages:    
    - install
    - build
    - cleanup_build 
    

variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR
  APP_OUTPUT_PATH: "$CI_PROJECT_DIR/artifacts/app"
  GIT_SUBMODULE_STRATEGY: recursive 

cache:
    key:
      files:      
         - package-lock.json
         - package.json
    paths:
      - node_modules 
    policy: pull

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
        - package.json
    paths:
      - node_modules
    policy: pull

install_dependencies:
    stage: install
    environment:
        name: staging
        url: http://188.166.214.118/app
    tags:
        - s1
    script:
      - npm install

  # Redefine cache to have default pull-push policy
    extends: .dependencies_cache
    cache:
      policy: pull-push
    only:
      changes:
        - package-lock.json 
        - package.json  

build:
    stage: build
    environment:
        name: staging
        url: http://188.166.214.118/app
    tags:
        - s1

    script:        
        - ng build --prod --aot --output-hashing=all --base-href /app/

    after_script:                 
        - echo "Build application complete" 

    artifacts:
      name: "app"
      paths:
        - $APP_OUTPUT_PATH
    extends: .dependencies_cache

    retry:
      max: 2
      when: always
    allow_failure: true        
       

cleanup_build_job:
    stage: cleanup_build
    script:
        - rm -rf $CI_BUILDS_DIR/*
        - exit 0
    when: on_failure
