version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: helpdesk
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    image: webangular:latest
    depends_on:
      - db
    ports:
      - "4200:4200"